Emilmoldovan24/Tue-Tweet

Tue_Tweet/.env, Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/resources/views/welcome.blade.php
Außerdem wurde eine Fähigkeit gelöscht, und zwar die Request old..., sollten die User aber noch machen!
Die Weiterführung klappt noch nicht, sh. UserController!
=> SignIn verbessert, aber noch nicht vollständig. 

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/database/migrations/2023_05_22_190201_create_users_table.php, Tue_Tweet/resources/views/dashboard.blade.php, Tue_Tweet/resources/views/welcome.blade.php
Ich musste die Authentifizierung anders im UserController prüfen, sowie einige Variabel-Namen umändern damit es das richtige der Datenbank entzieht. Möchte man auf die View feed gehen, kommen aber immer noch Fehler, die behoben werden müssen. Ich habe mich für die andere $request Abrufung entschieden, weil es mir leichter fällt.
Eine Migration hat gefehlt.
Außerdem habe ich eine TestSeite erstellt, die man simple aufrufen kann, um seine Funktionen zu testen (die benötigt nämlich nicht die Datenbank).
View feed richtig implementieren.
Auch ohne Änderung hat bei mir feed nicht funktioniert, da Luke es uns aber schonmal vorgezeigt hatte, bin ich mir nicht sicher, ob es an dem Aufbau meiner lokalen Datenbank hängt.
=> SignIn funktioniert nun.

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/public/assets/sql/Tue_tweet_Database.sql, Tue_Tweet/resources/views/feed.blade.php
Ich habe die Datenbank so angepasst das man mit ihr einfach auf die Auth  methoden zugreifen kann . 
Also wieder : 
- php artisan migrate:fresh
- php artisan db:seed --class=tweetSeeder
=> database change so we can check the id via Auth::id()

Tue_Tweet/app/Http/Controllers/FeedController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php, Tue_Tweet/routes/web.php
Für ein leichteres switchen der Seiten, habe ich einfache Buttons angelegt, schön wäre es aber auch wenn man mit back() arbeitet, falls wir mehrere Seiten haben, die auf das Profile zb. zugreifen, könnte man somit bessere Verzweigungen erstellen.
=> Routesbutton: 

Tue_Tweet/public/assets/sql/Tue_tweet_Database.sql
Ich habe die Sql file auf die Verfizierung angepasst und die visibility spalten hinzugefügt
bitte die Datenbank nach dem Pull neu aufsetzen .
-php artisan migrate:fresh
-php artisan db:seed --class=tweetSeeder
=> updated sqlfile

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/composer.lock, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/routes/web.php
Added Like/comment buttons and counts to the feed 
everything is already connected it to the DB
=> Added likes and comments to the feed

Tue_Tweet/app/Http/Controllers/UserController.php
=> Likes jetzt wirklich gefixt

Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/uiplay.blade.php, Tue_Tweet/routes/web.php
uiplayblade unnötige datei, war nur zum testen
=> uifeedchange

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/signup.blade.php, Tue_Tweet/resources/views/welcome.blade.php
Fehlermeldungen, die bei falschen Eingaben erscheinen definiert und geprintet. Hab es dem Design angepasst, aber die Darstellung könnte man trotzdem noch verschönern.
=> Validations

Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/routes/web.php
toggles the display of the comment via js function, I also added the counters for Likes Commis and Retweets (did that previously but there was a merge conflict)
=> Display comments

Tue_Tweet/resources/views/feed.blade.php
resolved merge conflict between the new feed UI and the new like and comment functions
=> fixed merge conflict btwn feedUI and usr functions

Tue_Tweet/composer.lock, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/welcome.blade.php
=> Valdidations

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/resources/views/feed.blade.php
default profile picture is chosen if User hasn't uploaded one yet
=> added default profile pictures

Tue_Tweet/app/Http/Controllers/AdminController.php, Tue_Tweet/routes/web.php
Added a hideTweet method in AdminController and a route.
method sets visibility of tweet to 0.
=> Added hideTweet method to set visibility of tweet to 0

Tue_Tweet/app/Http/Controllers/ProfileController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/routes/web.php
Added links from the usernames in the tweets on the feed to the profile page
=> Profile01fixed

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/public/assets/sql/Tue_tweet_Database.sql, Tue_Tweet/resources/views/settings.blade.php, Tue_Tweet/routes/web.php
-Änderung am Setting view der es ermöglicht die Profile_bio zu ändern (Controller, Route, view)
-Admin_id -> id
-Admin Dummie erstellt der mit dem Passwort "5555" aufgerufen werden kann 
Dies wurde unter anderem in der sql file gemacht also bitte wieder neu aufspielen 
php artisan migrate:fresh
php artisan db:seed --class=tweetSeeder
=> Update Profile and Admin

Tue_Tweet/app/Http/Controllers/UserController.php
username (and from there all userinformation) is now transmitted to the profile.blade by clicking on the username
=> fixed variable transmission to profile.blade

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/routes/web.php
posted images get added into the DB and are displayed in the feed with a dynamic size
=> added Function to tweet pictures

Tue_Tweet/resources/views/feed.blade.php
if clicked on Profile button you get redirected to the own profile page (as if you would clck on your own name in a tweet). The Username gets transmitted to the profil page, that you print all profil information there
=> profile button redirects to profile (with user_id)

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/resources/views/feed.blade.php
Nun kann man nur ein Bild posten, oder nur ein Text, beides oder gar nichts.
=> TweetWithoutText

Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php
Alles auf der ProfileSite zu sehen, aber keine Funktionalität
=> No Function, only Design

Tue_Tweet/public/assets/sql/Tue_tweet_Database.sql, Tue_Tweet/resources/views/feed.blade.php
Support für admins um user zu löschen die nach 30 tagen dann ganz gelöscht werden
=> deleting support for admins

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php, Tue_Tweet/routes/web.php
When a username is clicked on the profile page the tweets of this user (and all user info) are displayed. You can also like and comment on the profile page. Also the menu buttons on profile blade redirect to the right pages (Profile redirects to the own profile). I also removed some dummies.
=> implemented functions in profile

Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php
fixed profilePic overlapping with Username, removed redundant Code, aligned code and added comments (in feed.blade and profile.blade)
=> Profile pic fix

Tue_Tweet/public/assets/sql/Tue_tweet_Database.sql
-Nun sollte eine löschung auch wieder rückgängig gemacht werden können wenn man den deleted_at wert auf null setzt
=> update sql file

Tue_Tweet/app/Http/Controllers/UserController.php, Tue_Tweet/resources/views/profile.blade.php, Tue_Tweet/routes/web.php
on the profile page (if its not the own) there is a follow/unfollow button and follower counts, wich does what it says :)
=> implemented follow/unfollow/follow counts

Tue_Tweet/resources/views/signup.blade.php
=> Change Button Type 

Tue_Tweet/app/Http/Controllers/FeedController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/routes/web.php
Man kann jetzt Tweets editieren. Aber noch keine Bilder! Und Tweet wird wieder ganz nach oben angezeigt.
=> Edit tweet

Tue_Tweet/app/Http/Controllers/FeedController.php, Tue_Tweet/resources/views/feed.blade.php
Man muss halt immer ein Bild wieder auswählen, wenn man es behalten will. Müsste man sonst wieder mit JavScript dynamisch machen (ist schwer, aber beim Text wurde es auch gemacht).
=> Bilder kann man nun auch bearbeiten

Tue_Tweet/app/Http/Controllers/ProfileController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php, Tue_Tweet/routes/web.php
=> Profile Functions

Tue_Tweet/resources/views/feed.blade.php
like and comment function aren't working on retweets yet, because of a DB problem (tweet_id's and retweet_id's aren't unique)
=> retweets are now displayed on the feed

Tue_Tweet/app/Http/Controllers/AdminController.php, Tue_Tweet/resources/views/adminCreate.blade.php, Tue_Tweet/resources/views/adminFeed.blade.php, Tue_Tweet/resources/views/adminLogIn.blade.php, Tue_Tweet/routes/web.php
Added a where admins can be created
Added some buttons to admin login and adminfeed to naviigate
=> Added blade to create admins, added some buttons to navigate

Tue_Tweet/app/Http/Controllers/ProfileController.php, Tue_Tweet/resources/views/settings.blade.php, Tue_Tweet/routes/web.php
Ich habe in der setting seite eine funlktion eingeführt die alle daten von einem user als txt file speichert
=> Implement the data download function

Tue_Tweet/app/Http/Controllers/AdminController.php, Tue_Tweet/resources/views/adminCreate.blade.php, Tue_Tweet/resources/views/adminDashboard.blade.php, Tue_Tweet/resources/views/adminFeed.blade.php, Tue_Tweet/resources/views/adminUserFeed.blade.php, Tue_Tweet/routes/web.php
Created admin dashboard 
Created a blade where users can be managed (currently empty)
changed some buttons
=> Created admin dashboard, blade where user can be managed

Tue_Tweet/public/assets/sql/Tue_tweet_Database.sql
Neue spalten super_admin  (default false) 
und activated  (default true) in table admins
=> add two columns to admins

Tue_Tweet/public/assets/sql/Tue_tweet_Database.sql
Neue Spalte in Likes um tweets und retweets zu trennen
=> add new column to likes

Tue_Tweet/app/Http/Controllers/AdminController.php, Tue_Tweet/resources/views/adminUserFeed.blade.php
user feed for admins now working. 
Delete / restore users possible
=> User feed for admins now working

Tue_Tweet/app/Http/Controllers/AdminController.php, Tue_Tweet/resources/views/adminUserFeed.blade.php, Tue_Tweet/routes/web.php
in adminController is now a save as file function
Admins can safe user information as a .txt file on the manage users  blade
The files are safed in your \Tue-Tweet\Tue_Tweet\storage\app folder
filename is YYYY-MM-DD-HH-MM_USERID_USERNAME.txt
=> added export user as file

Tue_Tweet/app/Http/Controllers/UserController.php
retweet button is working as it should and images can be displyed in quoted tweets
Retweet must contain text (DB problem ig) !!
=> implemented retweet functition

Tue_Tweet/resources/views/adminCreate.blade.php, Tue_Tweet/resources/views/adminDashboard.blade.php, Tue_Tweet/resources/views/adminUserFeed.blade.php
Die create Admin seite wurde an das übrige desing angepasst.
Die seite ist im Dashbard nur für super admins sichtbar
=> create admin blade angepasst, adminDash angepasst

Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/settings.blade.php
=> colorchanges

Tue_Tweet/app/Http/Controllers/FeedController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php
Liking and commenting is now also possible on retwwets
=> Likes&comments on retweets

Tue_Tweet/app/Http/Controllers/FeedController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php, Tue_Tweet/routes/web.php
Ich habe delete Retweet aufm feed gemacht, sowie edit. Dann noch im profile den hide und unhide button korrigiert und HIDE/UNHIDE.
=> Edit retweet

Tue_Tweet/app/Http/Controllers/ProfileController.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php, Tue_Tweet/routes/web.php
Retweet Button redirects to feed and opens the retweet modal
=> retweets work from profile page

Tue_Tweet/app/Http/Controllers/ProfileController.php
Die downloads werden jetzt in den Standard downloads ordner geladen
=> files now downloaded to standard downloads

Tue_Tweet/app/Http/Controllers/ProfileController.php
Bugfix: Archived tweets wont show up on other users profile Page
=> other user's hidden tweets wont show on profile

Tue_Tweet/app/Http/Controllers/FeedController.php, Tue_Tweet/app/Notifications/UserNotifications.php, Tue_Tweet/database/migrations/2023_07_04_154019_create_notifications_table.php, Tue_Tweet/resources/views/feed.blade.php
Like Notifications get send to a Notification DB
=> Like Notifications are working (DB only)

Tue_Tweet/app/Http/Controllers/FeedController.php, Tue_Tweet/app/Http/Controllers/ProfileController.php, Tue_Tweet/resources/views/feed.blade.php
implemented follow and comment notifications (on feed only!!!!)
=> inplemented follow and comment notifications

Tue_Tweet/resources/views/adminFeed.blade.php, Tue_Tweet/routes/web.php
=> admin feed now with comment and img support

Tue_Tweet/resources/views/feed.blade.php
Fixed Bug, wich let follow-notified user not enter its account
=> fixed bug in follower notification

Tue_Tweet/resources/views/profile.blade.php
Bugfix: Like and commend buttons didn't work on profile, now they do.
=> Profile buttons bugfixes

Tue_Tweet/app/Http/Controllers/FeedController.php, Tue_Tweet/resources/views/profile.blade.php
Bugfix: You can now click on a notification thatz somebody retweeted your tweet and the RT get displayed, when the notification is clicked.
=> You can click on a RT noti and it gets displayed

Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php
Bugfix: Wrong PBs where shown in the comments
=> in comments the right profilepics are shown

Tue_Tweet/app/Http/Controllers/AdminController.php, Tue_Tweet/resources/views/adminCreate.blade.php, Tue_Tweet/routes/web.php
##Changes
Delete admin now soft delete
Activate / deactivate admins implemented
Admin cant log in if deleted / activated
=> delete Admins -> soft delete, activate / deactivate implemented

Tue_Tweet/app/Http/Kernel.php, Tue_Tweet/app/Http/Middleware/SuperAdmin.php, Tue_Tweet/resources/views/adminDashboard.blade.php, Tue_Tweet/routes/web.php
SuperAdmin.php middleware erstellt
checkt if admin is superadmin
\routes\web.php:
get('/adminCreate) ruft neue middleware auf
=> added authorization for createAdmin page

Tue_Tweet/app/Http/Controllers/UserController.php
=> deleted / deactivetad users cant login now

Tue_Tweet/resources/views/adminCreate.blade.php, Tue_Tweet/resources/views/adminDashboard.blade.php, Tue_Tweet/resources/views/adminLogIn.blade.php, Tue_Tweet/resources/views/adminUserFeed.blade.php, Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php, Tue_Tweet/resources/views/signup.blade.php, Tue_Tweet/resources/views/verify.blade.php, Tue_Tweet/resources/views/welcome.blade.php
-verify leitet direkt zu feed weiter wenn code korrekt
-minimale anpassungen von abständen (margins)
-löschung von unnötigen auskommentiertem code
=> fewChanges

Tue_Tweet/resources/views/feed.blade.php, Tue_Tweet/resources/views/profile.blade.php, Tue_Tweet/resources/views/signup.blade.php, Tue_Tweet/resources/views/verify.blade.php, Tue_Tweet/resources/views/welcome.blade.php
-überschriften in landing/sign-in page besser gemacht
-hier und da paar margins verändert
=> uiimprovements

Tue_Tweet/app/Http/Controllers/AdminController.php, Tue_Tweet/resources/views/adminCreate.blade.php, Tue_Tweet/resources/views/adminFeed.blade.php, Tue_Tweet/resources/views/adminUserFeed.blade.php, Tue_Tweet/routes/web.php
=> Admin small improvements
